"""empty message

Revision ID: 94effcee929b
Revises: 
Create Date: 2020-07-21 19:18:14.163567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94effcee929b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=100), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('quids', sa.Text(), nullable=True),
    sa.Column('su', sa.Integer(), nullable=True),
    sa.Column('subscription_expired', sa.Integer(), nullable=True),
    sa.Column('verify_code', sa.Integer(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('job_location', sa.String(length=128), nullable=True),
    sa.Column('post', sa.String(length=128), nullable=True),
    sa.Column('attachment', sa.String(length=128), nullable=True),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('experienced', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('udate', sa.DateTime(), nullable=True),
    sa.Column('mail_sent', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('candidate_tag',
    sa.Column('candidate_uid', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_uid'], ['candidate.uid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_tag')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('candidate')
    # ### end Alembic commands ###
